'use strict';
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const {pathToFileURL} = require('node:url');
const packageRoot = process.env.PLAYWRIGHT_PACKAGE_ROOT;
const {chromium} = packageRoot ? require(require.resolve('playwright', {paths: [packageRoot]})) : require('playwright');
const out = path.join(__dirname, 'qa-artifacts');
fs.mkdirSync(out, {recursive: true});
(async () => {
  const browser = await chromium.launch({headless: true});
  const report = {test_data_only: true, browser: await browser.version(), cases: [], network_requests: [], page_errors: []};
  for (const spec of [{name:'desktop',width:1440,height:1000},{name:'mobile',width:390,height:844}]) {
    const seen = new Set();
    for (let trial=0; trial<20 && seen.size<2; trial++) {
      const context = await browser.newContext({viewport: {width:spec.width,height:spec.height}, acceptDownloads: true});
      const page = await context.newPage();
      page.on('pageerror', e => report.page_errors.push(e.message));
      page.on('request', req => {if (/^https?:/.test(req.url())) report.network_requests.push(req.url());});
      await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href);
      assert.match(await page.locator('.notice').innerText(), /Investigator preview only/);
      await page.locator('#start').click();
      assert.match(await page.locator('#error').innerText(), /acknowledge/);
      await page.locator('#acknowledge').focus();
      await page.keyboard.press('Space');
      assert.equal(await page.locator('#acknowledge').isChecked(), true);
      await page.keyboard.press('Tab');
      assert.equal(await page.evaluate(()=>document.activeElement.id), 'start');
      await page.keyboard.press('Enter');
      assert.equal(await page.evaluate(()=>document.activeElement.tagName), 'H2');
      await page.locator('#preferences-next').click();
      assert.match(await page.locator('#error').innerText(), /certain/);
      await page.locator('#quiet-weight').focus();
      await page.keyboard.press('ArrowRight');
      assert.equal(await page.locator('#quiet-weight').inputValue(), '51');
      await page.locator('#preference-certainty').selectOption('high');
      await page.locator('#preferences-next').click();
      const arm = await page.locator('#aid').isVisible() ? 'reference_aided' : 'unaided';
      if (arm==='reference_aided') {
        assert.match(await page.locator('#aid').innerText(), /not a live AI/);
        assert.match(await page.locator('#aid').innerText(), /simple reference rule/);
      }
      const overflow = await page.evaluate(()=>({body: document.documentElement.scrollWidth, viewport:innerWidth}));
      assert(overflow.body<=overflow.viewport, JSON.stringify(overflow));
      if (!seen.has(arm)) await page.screenshot({path:path.join(out, spec.name+'-'+arm+'.png'),fullPage:true});
      await page.locator('#choice-next').click();
      assert.match(await page.locator('#error').innerText(), /select a hotel/);
      await page.locator('input[name="hotel"]').first().focus();
      await page.keyboard.press('Space');
      assert.equal(await page.locator('input[name="hotel"]').first().isChecked(),true);
      await page.keyboard.press('Tab');
      assert.equal(await page.evaluate(()=>document.activeElement.id),'choice-next');
      await page.keyboard.press('Enter');
      await page.locator('#outcomes-next').click();
      assert.match(await page.locator('#error').innerText(), /four short/);
      await page.locator('#fit').selectOption('4');
      await page.locator('#improvement').selectOption('travel');
      await page.locator('#clarity').selectOption('clear');
      await page.locator('#burden').selectOption('1');
      await page.locator('#outcomes-next').click();
      assert.match(await page.locator('#summary').innerText(), /not human evidence/);
      const fullDownload = page.waitForEvent('download');
      await page.locator('#export-full').click();
      const full = await fullDownload;
      assert.match(full.suggestedFilename(), /^PREVIEW-NOT-HUMAN-DATA-/);
      const raw = JSON.parse(fs.readFileSync(await full.path(),'utf8'));
      assert.equal(raw.record_type,'instrument_preview_not_human_evidence');
      assert.equal(raw.human_participation_verified,false);
      assert.equal(raw.informed_research_consent_collected,false);
      assert.equal(raw.assignment.arm,arm);
      assert.equal(raw.preferences.quiet_weight,51);
      assert.equal(raw.outcomes.future_improvement,'travel');
      const actionDownload = page.waitForEvent('download');
      await page.locator('#export-actions').click();
      const action=JSON.parse(fs.readFileSync(await (await actionDownload).path(),'utf8'));
      assert.equal(action.record_type,'instrument_preview_not_human_evidence');
      assert.equal(action.human_participation_verified,false);
      assert(!('preferences' in action)); assert(!('outcomes' in action));
      assert.equal(action.observed_choice.option_id,raw.choice.option_id);
      const storage = await page.evaluate(()=>({local:localStorage.length,session:sessionStorage.length}));
      assert.equal(storage.local,0); assert.equal(storage.session,0);
      await page.locator('#clear').click();
      await page.waitForLoadState();
      assert.equal(await page.locator('#step-0').isVisible(),true);
      assert.equal(await page.locator('#step-4').isVisible(),false);
      report.cases.push({viewport:spec.name,arm,trial,keyboard_checks_passed:true,full_export_checks_passed:true,action_export_checks_passed:true,horizontal_overflow:false});
      seen.add(arm);
      await context.close();
    }
    assert.equal(seen.size,2,'Both random arms were not seen for '+spec.name);
  }
  assert.deepEqual(report.page_errors,[]);
  assert.deepEqual(report.network_requests,[]);
  await browser.close();
  fs.writeFileSync(path.join(out,'browser-qa-results.json'),JSON.stringify(report,null,2)+'\n');
  console.log(JSON.stringify(report,null,2));
})().catch(e=>{console.error(e);process.exit(1);});
